-- Milestone 5A.2: persistent notification foundation.
--
-- This migration preserves the proven Milestone 4A registration and claim
-- workflows while adding transactional notification generation and private
-- notification read-state RPCs.
--
-- Included events:
--   * registration-submitted -> approved administrators
--   * account-approved       -> approved umpire (already generated by
--                               approve_umpire_profile in 202608050001)
--   * claim-submitted        -> approved administrators
--   * claim-approved         -> successful claimant
--
-- Manual assignment notification persistence is intentionally handled in the
-- later manual-assignment RPC conversion.

-- ============================================================================
-- 1. Private notification creation helpers
-- ============================================================================

create or replace function public.create_notification(
  p_organization_id uuid,
  p_type text,
  p_audience public.notification_audience,
  p_recipient_profile_id uuid,
  p_title text,
  p_message text,
  p_destination_page text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_notification_id uuid;
begin
  if p_organization_id is null then
    raise exception 'Notification organization is required';
  end if;

  if btrim(coalesce(p_type, '')) = '' then
    raise exception 'Notification type is required';
  end if;

  if p_audience is null then
    raise exception 'Notification audience is required';
  end if;

  if btrim(coalesce(p_title, '')) = '' then
    raise exception 'Notification title is required';
  end if;

  if btrim(coalesce(p_message, '')) = '' then
    raise exception 'Notification message is required';
  end if;

  if p_audience = 'account'
    and p_recipient_profile_id is null then
    raise exception 'Account notifications require a recipient profile';
  end if;

  if p_recipient_profile_id is not null
    and not exists (
      select 1
      from public.profiles profile
      where profile.id = p_recipient_profile_id
        and profile.organization_id = p_organization_id
    ) then
    raise exception 'Notification recipient was not found in this organization';
  end if;

  insert into public.notifications (
    organization_id,
    type,
    audience,
    recipient_profile_id,
    title,
    message,
    destination_page
  ) values (
    p_organization_id,
    btrim(p_type),
    p_audience,
    p_recipient_profile_id,
    btrim(p_title),
    btrim(p_message),
    coalesce(p_destination_page, '')
  )
  returning id into v_notification_id;

  return v_notification_id;
end;
$$;

revoke all on function public.create_notification(
  uuid,
  text,
  public.notification_audience,
  uuid,
  text,
  text,
  text
) from public;


create or replace function public.notify_organization_administrators(
  p_organization_id uuid,
  p_type text,
  p_title text,
  p_message text,
  p_destination_page text default ''
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_administrator record;
  v_created_count integer := 0;
begin
  if p_organization_id is null then
    raise exception 'Notification organization is required';
  end if;

  for v_administrator in
    select profile.id
    from public.profiles profile
    where profile.organization_id = p_organization_id
      and profile.role = 'administrator'
      and profile.status = 'approved'
    order by profile.id
  loop
    perform public.create_notification(
      p_organization_id,
      p_type,
      'admin'::public.notification_audience,
      v_administrator.id,
      p_title,
      p_message,
      p_destination_page
    );

    v_created_count := v_created_count + 1;
  end loop;

  return v_created_count;
end;
$$;

revoke all on function public.notify_organization_administrators(
  uuid,
  text,
  text,
  text,
  text
) from public;


-- ============================================================================
-- 2. Authenticated notification read-state RPCs
-- ============================================================================

create or replace function public.mark_notification_read(
  p_notification_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile_id uuid := public.current_profile_id();
  v_organization_id uuid := public.current_organization_id();
begin
  if v_profile_id is null
    or v_organization_id is null
    or not public.is_approved_account() then
    raise exception 'Approved authentication is required';
  end if;

  update public.notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id
    and organization_id = v_organization_id
    and recipient_profile_id = v_profile_id;
end;
$$;

revoke all on function public.mark_notification_read(uuid) from public;
grant execute on function public.mark_notification_read(uuid) to authenticated;


create or replace function public.mark_all_notifications_read()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile_id uuid := public.current_profile_id();
  v_organization_id uuid := public.current_organization_id();
begin
  if v_profile_id is null
    or v_organization_id is null
    or not public.is_approved_account() then
    raise exception 'Approved authentication is required';
  end if;

  update public.notifications
  set read_at = now()
  where organization_id = v_organization_id
    and recipient_profile_id = v_profile_id
    and read_at is null;
end;
$$;

revoke all on function public.mark_all_notifications_read() from public;
grant execute on function public.mark_all_notifications_read() to authenticated;


-- ============================================================================
-- 3. Registration submitted -> administrator notifications
-- ============================================================================

create or replace function public.provision_pending_umpire(
  p_invitation_code text,
  p_first_name text,
  p_last_name text,
  p_phone text default ''
)
returns public.profiles
language plpgsql
security definer
set search_path = pg_catalog, extensions, public
as $$
declare
  authenticated_user auth.users%rowtype;
  invitation public.organization_invitations%rowtype;
  existing_profile public.profiles%rowtype;
  created_profile public.profiles%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required';
  end if;

  select * into authenticated_user
  from auth.users
  where id = auth.uid();

  if not found or authenticated_user.email is null then
    raise exception 'Authenticated user was not found';
  end if;

  if authenticated_user.email_confirmed_at is null then
    raise exception 'Email verification is required';
  end if;

  select * into existing_profile
  from public.profiles
  where auth_user_id = auth.uid();

  if found then
    if existing_profile.role <> 'umpire'
      or existing_profile.status <> 'pending' then
      raise exception 'Authenticated user already has a non-pending profile';
    end if;

    return existing_profile;
  end if;

  if btrim(coalesce(p_first_name, '')) = ''
    or btrim(coalesce(p_last_name, '')) = '' then
    raise exception 'First and last name are required';
  end if;

  select * into invitation
  from public.organization_invitations
  where code_digest = digest(
      convert_to(btrim(p_invitation_code), 'utf8'),
      'sha256'
    )
    and revoked_at is null
    and expires_at > now()
    and use_count < max_uses
  for update;

  if not found then
    raise exception 'Invitation is invalid, expired, revoked, or fully used';
  end if;

  insert into public.profiles (
    organization_id,
    auth_user_id,
    role,
    status,
    first_name,
    last_name,
    email,
    phone
  ) values (
    invitation.organization_id,
    auth.uid(),
    'umpire',
    'pending',
    btrim(p_first_name),
    btrim(p_last_name),
    lower(authenticated_user.email),
    btrim(coalesce(p_phone, ''))
  )
  returning * into created_profile;

  update public.organization_invitations
  set use_count = use_count + 1
  where id = invitation.id;

  insert into public.activities (
    organization_id,
    actor_profile_id,
    type,
    action,
    subject,
    message,
    metadata
  ) values (
    created_profile.organization_id,
    created_profile.id,
    'account',
    'account_registered',
    concat_ws(
      ' ',
      created_profile.first_name,
      created_profile.last_name
    ),
    'Authenticated umpire registration submitted for approval.',
    jsonb_build_object(
      'invitationId',
      invitation.id
    )
  );

  perform public.notify_organization_administrators(
    created_profile.organization_id,
    'registration-submitted',
    'Registration Awaiting Approval',
    concat(
      concat_ws(
        ' ',
        created_profile.first_name,
        created_profile.last_name
      ),
      ' has registered and is awaiting approval.'
    ),
    'accounts'
  );

  return created_profile;
end;
$$;

revoke all on function public.provision_pending_umpire(
  text,
  text,
  text,
  text
) from public;

grant execute on function public.provision_pending_umpire(
  text,
  text,
  text,
  text
) to authenticated;


-- ============================================================================
-- 4. Claim submitted -> administrator notifications
-- ============================================================================

create or replace function public.submit_assignment_claim(
  p_assignment_id uuid
)
returns public.assignment_claims
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_organization_id uuid := public.current_organization_id();
  v_crew_member_id uuid := public.current_crew_member_id();
  v_assignment public.game_assignments;
  v_claim public.assignment_claims;
  v_game public.games;
  v_claimant public.crew_members;
begin
  if v_organization_id is null
    or v_crew_member_id is null
    or public.current_account_role() <> 'umpire'
    or not public.is_approved_account() then
    raise exception using
      errcode = 'P0001',
      message = 'claim_identity_required';
  end if;

  select * into v_assignment
  from public.game_assignments
  where id = p_assignment_id
    and organization_id = v_organization_id
  for update;

  if v_assignment.id is null
    or v_assignment.status <> 'open_for_claim'
    or v_assignment.locked then
    raise exception using
      errcode = 'P0001',
      message = 'assignment_already_claimed';
  end if;

  select * into v_game
  from public.games
  where id = v_assignment.game_id
    and organization_id = v_organization_id;

  if v_game.id is null then
    raise exception using
      errcode = 'P0001',
      message = 'claim_game_not_found';
  end if;

  select * into v_claimant
  from public.crew_members
  where id = v_crew_member_id
    and organization_id = v_organization_id;

  if v_claimant.id is null then
    raise exception using
      errcode = 'P0001',
      message = 'claimant_not_found';
  end if;

  insert into public.assignment_claims (
    organization_id,
    assignment_id,
    claimant_crew_member_id,
    status
  ) values (
    v_organization_id,
    v_assignment.id,
    v_crew_member_id,
    'pending'
  )
  returning * into v_claim;

  update public.game_assignments
  set status = 'pending_approval',
      updated_at = now()
  where id = v_assignment.id
    and organization_id = v_organization_id;

  perform public.notify_organization_administrators(
    v_organization_id,
    'claim-submitted',
    'Game Claimed',
    concat(
      concat_ws(
        ' ',
        v_claimant.first_name,
        v_claimant.last_name
      ),
      ' claimed ',
      v_assignment.position,
      ' for ',
      v_game.away_team,
      ' @ ',
      v_game.home_team,
      '.'
    ),
    'claims'
  );

  return v_claim;
end;
$$;

revoke all on function public.submit_assignment_claim(uuid) from public;
grant execute on function public.submit_assignment_claim(uuid) to authenticated;


-- ============================================================================
-- 5. Claim approved -> claimant notification
-- ============================================================================

create or replace function public.decide_assignment_claim(
  p_assignment_id uuid,
  p_decision public.claim_status,
  p_reason text default null
)
returns public.game_assignments
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_organization_id uuid := public.current_organization_id();
  v_profile_id uuid := public.current_profile_id();
  v_assignment public.game_assignments;
  v_claim public.assignment_claims;
  v_claimant_profile_id uuid;
  v_game public.games;
begin
  if v_organization_id is null
    or v_profile_id is null
    or not public.is_assigner_or_administrator() then
    raise exception using
      errcode = 'P0001',
      message = 'claim_decision_forbidden';
  end if;

  if p_decision is null
    or p_decision not in ('approved', 'rejected') then
    raise exception using
      errcode = 'P0001',
      message = 'invalid_claim_decision';
  end if;

  select * into v_assignment
  from public.game_assignments
  where id = p_assignment_id
    and organization_id = v_organization_id
  for update;

  if v_assignment.id is null
    or v_assignment.status <> 'pending_approval'
    or v_assignment.assigned_crew_member_id is not null
    or v_assignment.locked then
    raise exception using
      errcode = 'P0001',
      message = 'claim_no_longer_pending';
  end if;

  select * into v_claim
  from public.assignment_claims
  where organization_id = v_organization_id
    and assignment_id = v_assignment.id
    and status = 'pending'
  order by claimed_at, id
  limit 1
  for update;

  if v_claim.id is null then
    raise exception using
      errcode = 'P0001',
      message = 'claim_no_longer_pending';
  end if;

  update public.assignment_claims
  set status = p_decision,
      decision_by_profile_id = v_profile_id,
      decision_reason = nullif(btrim(p_reason), ''),
      decided_at = now(),
      updated_at = now()
  where id = v_claim.id
    and organization_id = v_organization_id;

  if p_decision = 'approved' then
    update public.assignment_claims
    set status = 'rejected',
        decision_by_profile_id = v_profile_id,
        decision_reason = 'Another claim was approved.',
        decided_at = now(),
        updated_at = now()
    where organization_id = v_organization_id
      and assignment_id = v_assignment.id
      and status = 'pending';

    update public.game_assignments
    set status = 'assigned',
        assigned_crew_member_id = v_claim.claimant_crew_member_id,
        locked = false,
        updated_at = now()
    where id = v_assignment.id
      and organization_id = v_organization_id
    returning * into v_assignment;

    select crew.profile_id
    into v_claimant_profile_id
    from public.crew_members crew
    where crew.id = v_claim.claimant_crew_member_id
      and crew.organization_id = v_organization_id;

    if v_claimant_profile_id is null then
      raise exception using
        errcode = 'P0001',
        message = 'claimant_profile_not_found';
    end if;

    select * into v_game
    from public.games
    where id = v_assignment.game_id
      and organization_id = v_organization_id;

    if v_game.id is null then
      raise exception using
        errcode = 'P0001',
        message = 'claim_game_not_found';
    end if;

    perform public.create_notification(
      v_organization_id,
      'claim-approved',
      'account'::public.notification_audience,
      v_claimant_profile_id,
      'Claim Approved',
      concat(
        'Your claim for ',
        v_assignment.position,
        ' on ',
        v_game.away_team,
        ' @ ',
        v_game.home_team,
        ' has been approved.'
      ),
      'my-schedule'
    );
  else
    update public.game_assignments
    set status = 'open_for_claim',
        assigned_crew_member_id = null,
        locked = false,
        updated_at = now()
    where id = v_assignment.id
      and organization_id = v_organization_id
    returning * into v_assignment;
  end if;

  return v_assignment;
end;
$$;

revoke all on function public.decide_assignment_claim(
  uuid,
  public.claim_status,
  text
) from public;

grant execute on function public.decide_assignment_claim(
  uuid,
  public.claim_status,
  text
) to authenticated;